### ISSUE TITLE
Audit modules with manually linking for RN 60 support

### ISSUE THREAD

**Issue by bweissbart** [brandingbrand/flagship#1050]
RN 60 introduced a new auto-linking scheme for native modules. As such, we should audit modules in which we have manual linking steps to see if they can be handled automatically in Flagship 9.

All of the following integrations are located in packages/flagship/src/lib/modules

- [ ] android/react-native-adobe-analytics
- [ ] android/react-native-camera
- [ ] android/react-native-code-push
- [ ] android/react-native-fcm
- [ ] android/react-native-firebase
- [ ] android/react-native-leanplum
- [ ] android/react-native-navigation
- [ ] android/react-native-sensitive-info
- [ ] android/react-native-zendesk-chat
- [ ] ios/react-native-adobe-analytics
- [ ] ios/react-native-code-push
- [ ] ios/react-native-firebase
- [ ] ios/react-native-leanplum

**Comment by Cauldrath** [comment]
react-native-adobe-analytics is no longer being maintained as of this year:
https://github.com/smalltownheroes/react-native-adobe-analytics

I did see that Adobe has their own React Native module:
https://github.com/adobe/react-native-acpanalytics

We could either fork and maintain react-native-adobe-analytics ourselves, or explore alternatives.

**Comment by Cauldrath** [comment]
react-native-fcm has been deprecated and only seems to be used in fsengagement. We should convert it to use react-native-firebase.
