### ISSUE TITLE
Gridlines are misaligned between products in Product Index

### ISSUE THREAD

**Issue by nathan-sankbeil** [brandingbrand/flagship#143]
Happens when the product item heights differ (eg. product name wrapping, only some products having reviews, etc).

![screen shot 2018-08-08 at 1 10 55 pm](https://user-images.githubusercontent.com/3847536/43852924-9222cd8c-9b0c-11e8-8f1f-3657b1e82458.png)

**Comment by bweissbart** [comment]
Fixed in #854
