### ISSUE TITLE
Development version number should be fixed to the bottom of viewport for web

### ISSUE THREAD

**Issue by nathan-sankbeil** [brandingbrand/flagship#144]
Currently shows after the last element on the page, so it's annoying to access on pages with a lot of content.

![screen shot 2018-08-08 at 1 17 48 pm](https://user-images.githubusercontent.com/3847536/43853294-b9ce21f0-9b0d-11e8-80dd-95c213410c7f.png)

**Comment by bweissbart** [comment]
Fixed by #857
