### ISSUE TITLE
fix padding state & prop implementation in fscomponents Accordion.tsx

### ISSUE THREAD

**Issue by sdenaci** [brandingbrand/flagship#170]
the padding prop is supposed to be passed to state & then implemented as left, right & bottom padding, but it is not being passed and instead the padding is always set to the default 15 pixels.
![screen shot 2018-08-16 at 3 44 54 pm](https://user-images.githubusercontent.com/23608557/44231367-e461fe00-a16b-11e8-982a-d3457e46bcc0.png)

**Comment by ralmidani** [comment]
Taking a look at this.

`paddingBottom` is not part of the `AccordionState` interface, just `paddingLeft` and `paddingRight`. Should it be added to the interface?

In `getDerivedStateFromProps` (and in the `constructor` for that matter--should we be duplicating the state-setting logic or centralizing it in one method?), the || operator coerces 0 to false, so the default will be chosen. Should we instead be using the ternary operator and strict equality to check for `undefined`?

**Comment by ralmidani** [comment]
@sdenaci Thank you for your response!

My understanding is getDerivedStateFromProps runs once, between the constructor and the first render. So we should be OK in terms of re-renders.

Perhaps for now we should keep the setting/derivation of state as-is (changing the patterns will make the larger codebase inconsistent), and create a separate issue for updating the entire project to use newer patterns and best practices?

**Comment by bweissbart** [comment]
Closing per above comments.
