### ISSUE TITLE
React-native-camera package fails to build

### ISSUE THREAD

**Issue by pavlemilicevicbb** [brandingbrand/flagship#213]
Steps to reproduce:

* Download `react-native-camera'
* Init project
* Run project using `yarn android`

FAILURE: Build failed with an exception.
* What went wrong:
Failed to capture snapshot of input files for task ':react-native-camera:compileReleaseAidl' property 'importDirs' during up-to-date check.
> The library com.google.android.gms:play-services-basement is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 12.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

**Comment by nathan-sankbeil** [comment]
This is only fixed if you're also using react-native-firebase or another module that upgrades gradle.
