### ISSUE TITLE
FSApp Router popTo

### ISSUE THREAD

**Issue by crherman7** [brandingbrand/flagship#2220]
# popTo

## Summary

The router navigation should contain similar functionality to known navigation libraries such as `react-native-navigation` since this is an abstraction of `react-native-navigation`. One key function that is missing is `popTo`. A component shouldn't have to know how many indexes back in the stack it wants to navigate to utilizing `go`. `popTo` implementation should pop to the most recent path in the stack.

## Basic example

```
type PopTo = (path: string) => void;

popTo('/cart');
```

## Motivation

A simpler way and decoupled way to pop to the most recent path in the stack.

## Detailed design

Utilizing the `this.store` object from https://github.com/brandingbrand/flagship/blob/95a34b2582be6f41c2310a1dca95c2f2f20fc021/packages/fsapp/src/beta-app/router/history/history.ts#L66 - you should be able to find the location and index that you would need to pop to given the path value. The utilize `updateLocation` with the new location in stack https://github.com/brandingbrand/flagship/blob/95a34b2582be6f41c2310a1dca95c2f2f20fc021/packages/fsapp/src/beta-app/router/history/history.ts#L343.

## Drawbacks

There are no drawbacks since this would be a simpler decoupled approach to going to the most recent supplied stack in the stack. This is of course with the understanding that it's the most recent index.

## Alternatives

The alternative approach right now is to utilize `go: (index: number) => void;` which couples the component to knowing the stack history.

**Comment by wSedlacek** [comment]
`.open()` does something similar to your expectations of `.popTo()` already.
It ill look for the route in either the active stack or the stack where that route has tab affinity and pop to it.
If the route doesn't exist it will open up the route either on the current stack or the stack where it has tab affinity.

`.popTo()` seems like it would behave in a similar way, expect not having the fallback for opening the route if it doesn't exist.
Thinking about how it would be used I have a few questions about UX.

1. Given that any route can be an entry point, even routes like `/orders/:id/confirmation` what would the expectation be if a user entered on that route then pressed a button linked to a back to that didn't exist on the stack?

2. Would the expectations of this behavior differ in a web context such as a PWA where you have a single stack?

**Comment by crherman7** [comment]
Closing due to `open` universally handles pop or push.
