### ISSUE TITLE
[Bug Report] Missing Recommended Icons 

### ISSUE THREAD

**Issue by crherman7** [brandingbrand/flagship#2638]
## Expected Behavior

No warnings should be shown when uploading to TestFlight.

## Actual Behavior

```
ITMS-90892: Missing recommended icon - The bundle does not contain alternate app icon for iPad of exactly '167x167' pixels...
```

```
ITMS-90892: Missing recommended icon - The bundle does not contain alternate app icon for iPad of exactly '152x152' pixels...
```

## Steps to Reproduce the Problem

  1. Targeted Device Family: 1,2 i.e. universal
  2. Upload to TestFlight

## Specifications

  - Version: @brandingbrand/code-core: 12.0.1
  - Platform: react-native 0.71.+
  - Subsystem: @brandingbrand/code-plugin-app-icon: 1.0.0

## Solution / Workaround
Update rules https://github.com/brandingbrand/flagship/blob/main/packages/plugin-app-icon/src/utils/rules/ios.ts to add the 167 and 152 with 2x scaling respective resolutions.

**Comment by jasonmosley** [comment]
@crherman7 Has this been resolved with v13?

**Comment by crherman7** [comment]
> @crherman7 Has this been resolved with v13?

no, this has not been resolved in the app-icon plugin. I will put up a PR for this.

**Comment by crherman7** [comment]
We cover these already:
- https://github.com/brandingbrand/flagship/blob/7c88cd6a23c2bb387c03ae3e876f7bf9b543c1be/packages/plugin-app-icon/src/rules.ts#L16
- https://github.com/brandingbrand/flagship/blob/7c88cd6a23c2bb387c03ae3e876f7bf9b543c1be/packages/plugin-app-icon/src/rules.ts#L27

the error points to alternate app icons, there are no warnings in xcode and those icons are fulfilled.

<details>
  <summary>xcode</summary>
  
<img width="1141" alt="Screenshot 2024-06-27 at 12 26 26 PM" src="https://github.com/brandingbrand/flagship/assets/17734240/e2d12b75-b5c5-4c20-bb66-d97873c72f30">
</details>
