### ISSUE TITLE
Issue with boxes

### ISSUE THREAD

**Issue by Red-Cross-Knight** [brandingbrand/flagship#2641]
Was taking another crack at automating quotes, however when entering box sizes I get these errors on one specific line:
![image](https://github.com/brandingbrand/flagship/assets/1887734/9ac7db06-4352-4b43-82f3-7254362089ed)

Not matter what I change the value to be I always get a similar range, if i try to duplicate down to the last digit same error. 

Currently running Flagship Version 3.0.21

**Comment by Red-Cross-Knight** [comment]
Possibly related, did manage to get it to save after changing the Supported weight to 0,and leaving box weight empty, however once saved all values change to what is seen below which appear to be in lb's, this would be fine, but now I have a box weight in grams and a empty box weight in lbs, I would expect these would remain in grams for consistency. 

![image](https://github.com/brandingbrand/flagship/assets/1887734/d4d72aec-5abd-49fc-adb0-2afcbac135bb)

**Comment by jasonmosley** [comment]
@Red-Cross-Knight I believe you posted this issue in the wrong repo. I am going to be closing this issue since it is not related to our React Native configuration framework.
