### ISSUE TITLE
Use react-native-fast-image

### ISSUE THREAD

**Issue by justin-endler** [brandingbrand/flagship#325]
In order to inherit better memory management with images, convert flagship to use react-native-fast-image in place of the built-in Image component. This includes converting flagship components to it's use as well as usage in component stories and example apps (pirateship).

**Comment by bweissbart** [comment]
After additional research we determined that react-native-fast-image stores all images in memory which makes it not appropriate for pages with a large amount of issues. Regular RN images should be used within something such as a FlatList with clipping enabled.
