### ISSUE TITLE
Add Barcode scanner component

### ISSUE THREAD

**Issue by DavidRhodesBB** [brandingbrand/flagship#338]
Include overlay or framing with text for context, like Amazon or BestBuy. Would be used in product search:
![img_882d600ab8cd-1 2](https://user-images.githubusercontent.com/41645989/51774136-2f8b2000-20bf-11e9-9e5c-1682ed7605ae.jpeg)

**Comment by bweissbart** [comment]
We need to flesh this out more so I'm recommending we don't start work on it yet.
