### ISSUE TITLE
Add Expandable Store Hours/Details

### ISSUE THREAD

**Issue by DavidRhodesBB** [brandingbrand/flagship#339]
As with Google Maps when viewing a retail store....By default today's hours show, with a dropdown for the full week's store hours, and today's bolded. Optional features would be to put the day of the week that is 'today' at the top of the list, then sort, as opposed to M-Sun, and displaying "open now" or "closed now" based on client time.

Gist: https://gist.github.com/DavidRhodesBB/5821347c46396f1f564d9bfe85cdd607

![screen shot 2019-01-25 at 4 21 28 pm](https://user-images.githubusercontent.com/41645989/51773727-be973880-20bd-11e9-9c59-83f579da937d.png)
![screen shot 2019-01-25 at 4 22 51 pm](https://user-images.githubusercontent.com/41645989/51773731-c2c35600-20bd-11e9-9043-6b0c478b022d.png)

**Comment by bweissbart** [comment]
Resolved by #908
