### ISSUE TITLE
Add non-FlatList Grid Component

### ISSUE THREAD

**Issue by bweissbart** [brandingbrand/flagship#344]
https://github.com/brandingbrand/flagship/blob/master/packages/fscomponents/src/components/Grid.tsx

The Grid component, as currently implemented above, utilizes a FlatList. This was most likely done because it was intended to be used in interfaces that are expected to scroll, such as Product and Category index pages.

However, projects are using Grid as a table view, and in most cases don't expect it to be using a FlatList behind the scenes. We should make a component that simply displays table data separated by optional grid lines that doesn't implement a FlatList or ScrollView on its own.

**Comment by OlgaKutovaya** [comment]
@bweissbart we have already fixed this issue #885

**Comment by bweissbart** [comment]
Fixed with #885
