### ISSUE TITLE
Multicarousel's onLayout adjusts the width of the container repeatedly

### ISSUE THREAD

**Issue by Cauldrath** [brandingbrand/flagship#385]
https://github.com/brandingbrand/flagship/blob/50d491f016a9eed1eee858c351a4c2e8756101b3/packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx#L204

`handleContainerSizeChange` is run when the overall carousel and the individual items have their size changed. This function adjusts the itemWidth and containerWidth state, which can change the size of the items, which in turn causes `handleContainerSizeChange` to run again. This causes the items to be rerendered repeatedly.

**Comment by bweissbart** [comment]
Fixed with https://github.com/brandingbrand/flagship/pull/849
