### ISSUE TITLE
Change env logic for web

### ISSUE THREAD

**Issue by bweissbart** [brandingbrand/flagship#403]
The logic for handling the default environment differs between native and web in ways that are not predicable to users coming from native to web or from web to native.

In native, when an environment is specified via the `--env` parameter during init, the specified environment is saved as a Native Constant in the generated iOS or Android project; this environment will then be selected when the app is started for the first time.

In web, the current environment is saved to Local Storage. However, when `init` is run with an `--env` parameter, the environment value isn't changed the Bash script doesn't have the ability to overwrite the value in Local Storage.

The current logic of the web env-switcher is to default to prod unless another value already exists in Local Storage: https://github.com/brandingbrand/flagship/blob/master/packages/fsapp/src/lib/env-switcher.web.ts#L6

We should change how environments are handled in web so it's possible to change the default environment via the `init` script without breaking the environment switcher.

**Comment by Cauldrath** [comment]
Addressed by https://github.com/brandingbrand/flagship/pull/870
