### ISSUE TITLE
Metro bundler should not watch src folder

### ISSUE THREAD

**Issue by VanceHubb** [brandingbrand/flagship#452]
Metro bundler is currently watching src folder and will trigger a live-reloading event when there is a ts file being saved. However, we are expecting the event to be only fired after `tsc` watch compiled `src` to `dist`. This conflict causes inconsistency between `src` and `dist` until the user saves the file again.

Need to exclude the `src` folder or only watch `dist` folder, whichever is more appropriate

**Comment by vancehu** [comment]
since metro bundler supports typescript source files,  all we need to do is (pirateship and actual projects):
1. not emitting `dist` folder in tsconfig 
2. set entry point to import `src` instead of `dist` folder
And the issue above can be fixed
