### ISSUE TITLE
Add sideEffects flag to each package.json

### ISSUE THREAD

**Issue by bweissbart** [brandingbrand/flagship#460]
We need to add the following property to each package.json in the packages directory:

`"sideEffects": false`

This tells Webpack that the package is free from side effects and therefore can be safely tree shaken.

https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by DavidRhodesBB** [comment]
https://github.com/brandingbrand/flagship/commit/5f325e147171726ec2e2bf156313f0eaa4460ed2

merged - thanks @bweissbart!
