### ISSUE TITLE
refactor CreditCardNumber to avoid getDerivedStateFromProps

### ISSUE THREAD

**Issue by DavidRhodesBB** [brandingbrand/flagship#567]
running credit card form in storybook results in this warning, with good guidance:

`Warning: `CreditCardNumber` uses `getDerivedStateFromProps` but its initial state is undefined. This is not recommended. Instead, define the initial state by assigning an object to `this.state` in the constructor of `CreditCardNumber`. This ensures that `getDerivedStateFromProps` arguments have a consistent shape.`

**Comment by bweissbart** [comment]
All of the logic currently in getDerivedStateFromProps could be moved into a `onChangedText` handler in the `TextInputMask` props.

Applicable file: https://github.com/brandingbrand/flagship/blob/develop/packages/fscomponents/src/components/CreditCardNumber.tsx#L117

TextInputMask example: https://github.com/benhurott/react-native-masked-text

**Comment by sentiurin** [comment]
@deemaabdallah Changes for this issue (like in closed PR: #578) already in develop branch: https://github.com/brandingbrand/flagship/blob/a2750ab4dc1f574a26e2265e795fd7b115643701/packages/fscomponents/src/components/CreditCardNumber.tsx#L93

So it's fixed.

**Comment by bweissbart** [comment]
Fixed with #926.
