### ISSUE TITLE
fscomponents should have a ProgressiveImage component

### ISSUE THREAD

**Issue by dfrho** [brandingbrand/flagship#585]
...that renders a blurred thumbnail version of Image or ImageWithOverlay instead of loader while full image loads, popularized by Medium. Animated transition, something like this: https://medium.com/react-native-training/progressive-image-loading-in-react-native-e7a01827feb7

**Comment by Cauldrath** [comment]
React-native has defaultSource, which can render a different image while the larger one loads:
https://facebook.github.io/react-native/docs/image.html#defaultsource
